version: '3'

services:
  react-ts:
    build: ./docker/react-ts
    ports:
      - '3000:3000'
    volumes:
      - './react-ts-app:/app/react-ts'
    tty: true
    stdin_open: true
    
  go:
    build: ./docker/golang
    ports:
      - '8000:8000'
    volumes:
      - './go-app://app/go'
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    