version: '3'

services:
  react-ts:
    build: ./docker/react-ts
    ports:
      - '3000:3000'
    volumes:
      - './react-ts-app:/app/react-ts'
    tty: true
    stdin_open: true
    
  go:
    build: ./docker/golang
    ports:
      -'8080:8080'
    volumes:
      - './go-app://app/go'
    tty: true
    stdin_open: true
  