// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       int    `json:"id"`
	Comment  string `json:"comment"`
	Likes    int    `json:"likes"`
	User     *User  `json:"user"`
	PostDate string `json:"postDate"`
}

type Episode struct {
	ID   int `json:"id"`
	Date int `json:"date"`
}

type NewComment struct {
	EpisodeID int    `json:"episodeID"`
	Comment   string `json:"comment"`
	UserID    int    `json:"userID"`
}

type Program struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type QueryEpisodesInput struct {
	ProgramID int `json:"programID"`
	FromDate  int `json:"fromDate"`
	ToDate    int `json:"toDate"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
