name: CI Workflow for tv-comment-app

on: [push]

jobs:
  go_server_test:
    name: go server test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./go-app/server

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: "test_go_tvapp"
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run test
      env:
          MYSQL_PASSWORD: root
          MYSQL_USER: root
          DATABASE_NAME: test_go_tvapp
          HOST: localhost
          CLIENT_ORIGIN: http://localhost:3000
      run: |
        go test ./dbcontrol -v