name: CI Workflow for tv-comment-app

on: [push]

jobs:
  go_server_test:
    name: go server test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./go-app/server

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run test
      run: |
        go test ./... -v